version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
    - 3333:3333
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
      MYSQL_DATABASE: adonis